### ISSUE TITLE
Image Loader : Layout

### ISSUE THREAD

**Issue by oskaraqp** [BowlerHatLLC/feathers#1472]
I have an horizontal layout and inside two vertical layouts, first one with text and the second one and image, previosly setting the layoutdata of the image to new VerticalLayoutData(100), was working ok with the latest change the image is simple shown at its normal size going beyond the limits of the main horizontal layout, if I set VerticalLayoutData(100,100); it is resized but moved all the way to the right going out of borders, again this bug was added in the last commit, did somethign has changed to set layout on image loaders, by the way other loaders are failling too, only those which  are not nested and vertical are working normally.

**Comment by joshtynjala** [comment]
Thanks! I'll take a look.

**Comment by oskaraqp** [comment]
You're welcome josh, sorry if I cannot help more, I didn't update my files since some days ago so no sure where the issue came from, I see there has been this change : ImageLoader: calculates minimum dimensions separately so that they work in layouts with percentWidth and percentHeight
Maybe that one changed something, I also see layouts have got some changes.

**Comment by joshtynjala** [comment]
Alright, the latest commits should get that issue fixed. Sorry about that!

Unfortunately, the bug(s) snuck into Feathers 3.1.0-beta before I heard from you, so you'll want to keep using the source from Github.

**Comment by oskaraqp** [comment]
Yes Ive used the files from github the ones Ive downloaded today have the bug reported, Ill keep using my old files until this issue is fixed, any idea when that will happen?

**Comment by joshtynjala** [comment]
The issue is fixed. I was simply trying to say that I also released version 3.1.0-beta today, but it does not include the fix. The fix is only on Github.

**Comment by oskaraqp** [comment]
Awesome, Ill give it a try and let you know how it works with the fix. Thank you.

**Comment by oskaraqp** [comment]
Hi Josh the issue was fixed but now imageloader is giving this error
Error: com.views.components.screencontents::PainPointScreenContent returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.
	at feathers.core::FeathersControl/invalidate()[C:\Trabajo\packages\Starling 2.0\feathers\core\FeathersControl.as:1964]
	at feathers.controls::LayoutGroup/child_resizeHandler()[C:\Trabajo\packages\Starling 2.0\feathers\controls\LayoutGroup.as:1048]
	at starling.events::EventDispatcher/invokeEvent()[C:\Trabajo\packages\Starling 2.0\starling\events\EventDispatcher.as:147]
	at starling.events::EventDispatcher/dispatchEvent()[C:\Trabajo\packages\Starling 2.0\starling\events\EventDispatcher.as:118]
	at starling.display::DisplayObject/dispatchEvent()[C:\Trabajo\packages\Starling 2.0\starling\display\DisplayObject.as:617]
	at starling.events::EventDispatcher/dispatchEventWith()[C:\Trabajo\packages\Starling 2.0\starling\events\EventDispatcher.as:196]
	at feathers.core::FeathersControl/saveMeasurements()[C:\Trabajo\packages\Starling 2.0\feathers\core\FeathersControl.as:2316]
	at feathers.controls::ImageLoader/autoSizeIfNeeded()[C:\Trabajo\packages\Starling 2.0\feathers\controls\ImageLoader.as:1778]
	at feathers.controls::ImageLoader/draw()[C:\Trabajo\packages\Starling 2.0\feathers\controls\ImageLoader.as:1640]
	at feathers.core::FeathersControl/validate()[C:\Trabajo\packages\Starling 2.0\feathers\core\FeathersControl.as:2013]
	at feathers.controls::LayoutGroup/validateChildren()[C:\Trabajo\packages\Starling 2.0\feathers\controls\LayoutGroup.as:973]
	at feathers.controls::LayoutGroup/draw()[C:\Trabajo\packages\Starling 2.0\feathers\controls\LayoutGroup.as:718]
	at com.views.components.screencontents::PainPointScreenContent/draw()[C:\Trabajo\bluepony\Xylem - Transparent\src\com\views\components\screencontents\PainPointScreenContent.as:103]
	at feathers.core::FeathersControl/validate()[C:\Trabajo\packages\Starling 2.0\feathers\core\FeathersControl.as:2013]
	at feathers.core::ValidationQueue/advanceTime()[C:\Trabajo\packages\Starling 2.0\feathers\core\ValidationQueue.as:168]
	at starling.animation::Juggler/advanceTime()[C:\Trabajo\packages\Starling 2.0\starling\animation\Juggler.as:354]
	at starling.core::Starling/advanceTime()[C:\Trabajo\packages\Starling 2.0\starling\core\Starling.as:402]
	at starling.core::Starling/nextFrame()[C:\Trabajo\packages\Starling 2.0\starling\core\Starling.as:387]
	at starling.core::Starling/onEnterFrame()[C:\Trabajo\packages\Starling 2.0\starling\core\Starling.as:601]

I don't have anything on draw method or resizing are changing any size in fact I have a flag which allows me to add a videloader or the image but only the imageloader gives the problem,

What I've found so far is that I was previosuly setting my layouts like this :
_image.layoutData = new VerticalLayoutData(60);
but I get those errors or wrong positioned, changing to this :
_image.layoutData = new VerticalLayoutData(60, 100);
fixes the issue, so far this is no a bug I think but people needs to be aware of the problem maybe.
Thank you

**Comment by oskaraqp** [comment]
by the way I still have issues with the image itself which I set _imageVerticalLayoutData.percentWidth = 100; but still the images are never shown at the border of the view there's always some padding on the left, I'm checking the horizontalalign or any paddings but none is changed.

**Comment by joshtynjala** [comment]
Can you share some code that will reproduce these issues? Not a whole projectbutit also not something that requires guesswork. Preferably, something that I can simply paste into my editor and test quickly. Thank you!

**Comment by oskaraqp** [comment]
protected override function initialize():void
		{
			super.initialize();
			trace(this, "initialize");
			
			_verticalLayoutData = new VerticalLayoutData();
			_verticalLayoutData.percentWidth = 100;
			//_verticalLayoutData.percentHeight = 100;
			
			verticalLayout.gap = 10;//this only sets my vertical object
			verticalLayout.paddingLeft = verticalLayout.paddingRight = ApplicationData.SCREEN_CONTENT_BORDER;
			verticalLayoutData.percentWidth = 100;
			verticalLayoutData.percentHeight = 100;
			
			
			_topContainer = new LayoutComponent();
			_topContainer.horizontalLayout.gap = 0;
			_topContainer.verticalLayoutData.percentWidth = 100;
			addChild(_topContainer);
				
			var _titleLayoutData:HorizontalLayoutData = new HorizontalLayoutData();
			_titleLayoutData.percentWidth = 100;
			
			_title = new Title2Label();
			_title.layoutData = _titleLayoutData;
			_title.text = _vo.title;
			_title.wordWrap = true;
			_topContainer.addChild(_title);
			
			if (_voLeft != null) {
				_moveLeftButton = new ButtonPainPointMove();
				_moveLeftButton.vo = _voLeft;
				_moveLeftButton.defaultIcon = new Image(Assets.manager.getTexture("Btn_Arrow Left"));
				_moveLeftButton.layoutData = new HorizontalLayoutData(NaN);
				_topContainer.addChild(_moveLeftButton);
			}
			
			if (_voRight != null) {
				_moveRightButton = new ButtonPainPointMove();
				_moveRightButton.vo = _voRight;
				_moveRightButton.defaultIcon = new Image(Assets.manager.getTexture("Btn_Arrow Right"));
				_moveRightButton.layoutData = new HorizontalLayoutData(NaN);
				_topContainer.addChild(_moveRightButton);
			}
			
			_closeButton = new ButtonPainPointClose();
			_closeButton.layoutData = new HorizontalLayoutData(NaN);
			_topContainer.addChild(_closeButton);
			
			if (_vo.text != null) {
				_text = new Text1Label();
				_text.text = _vo.text;
				_text.wordWrap = true;
				_text.layoutData = _verticalLayoutData;
				addChild(_text);
			}
			
					_image = new ImageLoader();
					var _imageVerticalLayoutData:VerticalLayoutData = new VerticalLayoutData();
					_imageVerticalLayoutData.percentWidth = 50;
					_imageVerticalLayoutData.percentHeight = NaN;
					_image.layoutData = _imageVerticalLayoutData;
					//_image.scaleMode = ScaleMode.NO_BORDER
					_image.source = Assets.manager.getTexture(_vo.media.url);
					addChild(_image);

			var i:uint = 0;
			
			if (_vo.systemButtons.length > 0 ) {
				_systemButtonsText = new Title3Label();
				_systemButtonsText.text = ApplicationData.SCREEN_PAIN_POINT_RECOMMENDED;
				_systemButtonsText.layoutData = _verticalLayoutData;
				addChild(_systemButtonsText);
				
				_systemButtonsContainer = new LayoutComponent();
				_systemButtonsContainer.horizontalLayout.gap = ApplicationData.SCREEN_CONTENT_BORDER;
				_systemButtonsContainer.verticalLayoutData.percentWidth = 100;
				
				addChild(_systemButtonsContainer);
				
				for (i = 0; i < _vo.systemButtons.length; i++) {
					var _buttonSystem:ButtonSystem = new ButtonSystem();
					_buttonSystem.vo = _vo.systemButtons[i];
					_systemButtonsContainer.addChild(_buttonSystem);
				}
			}
			if (_vo.exploreMoreButtons.length > 0 ) {
				_exploreMoreButtonsText = new Title3Label();
				_exploreMoreButtonsText.text = ApplicationData.SCREEN_PAIN_POINT_EXPLORE;
				_exploreMoreButtonsText.layoutData = _verticalLayoutData;
				addChild(_exploreMoreButtonsText);
				
				_exploreMoreButtonsContainer = new LayoutComponent();
				_exploreMoreButtonsContainer.horizontalLayout.gap = ApplicationData.SCREEN_CONTENT_BORDER;
				_exploreMoreButtonsContainer.verticalLayoutData.percentWidth = 100;
				
				addChild(_exploreMoreButtonsContainer);
				
				for (i = 0; i < _vo.exploreMoreButtons.length; i++) {
					var _buttonExplore:ButtonExploreMore = new ButtonExploreMore();
					_buttonExplore.vo = _vo.exploreMoreButtons[i];
					_exploreMoreButtonsContainer.addChild(_buttonExplore);
				}
				
			}
		}

**Comment by oskaraqp** [comment]
I'm sorry I cannot put something that you can copy and paste but I think this gives you an idea of the implementation, I'll be glad to answer questions.

**Comment by joshtynjala** [comment]
Can you try the most recent commits and let me know if things are better? Thanks!

**Comment by oskaraqp** [comment]
Awesome problem is fixed now, I can use this :
var _imageVerticalLayoutData:VerticalLayoutData = new VerticalLayoutData();
_imageVerticalLayoutData.percentWidth = 50;
_imageVerticalLayoutData.percentHeight = NaN;
and no inifite loop error and it uses half of the area as expected, thank you sooo much.
